### ISSUE TITLE
Patching Wearable App creates conflict with watch plugin.

### ISSUE THREAD

**Issue by wiredroid** [adil192/SamsungAppsPatcher#13]
Watch 4 Plugin

To reproduce error: 
Install wearable app, pair watch, wait for wearable app to download plugin. Plugin is unable to be installed because package name conflicts with wearable package name.

![Screenshot_20220831-095705_Package installer](https://user-images.githubusercontent.com/86910506/187563943-b25022fa-9de7-4b5d-85ba-4ff2375a10cd.png)

**Comment by wiredroid** [comment]
Sorry for this just realised every APK has to be patched. Hanging on patching samsung check in watch4plugin.

**Comment by adil192** [comment]
Hi wiredroid, Watch4 doesn't work with this project sorry!
