### ISSUE TITLE
wearable-patcher.sh: line 24: apktool: command not found

### ISSUE THREAD

**Issue by yellmehus** [adil192/SamsungAppsPatcher#18]
As you said, I installed all the necessary things, including apktool, but I am getting this error. I also added the apktool to all Path sections, but it doesn't work on WSL at all.
![image](https://user-images.githubusercontent.com/99523377/189735408-bb2d753f-a45b-43b1-b569-fdedccb24b72.png)

**Comment by adil192** [comment]
It seems like bash doesn't have access to apktool. I'm not familiar with WSL so I can't help you with specifics, but maybe bash has a separate PATH to configure?

**Comment by yellmehus** [comment]
So is there any other way you would suggest me to do this, mate?

**Comment by adil192** [comment]
Again, this seems more like an issue with your setup than an issue with my script. This is something you'll need to figure out yourself
