### ISSUE TITLE
Can't sign in to Samsung Health

### ISSUE THREAD

**Issue by V3semir** [adil192/SamsungAppsPatcher#2]
![Screenshot_20220326-173319_Samsung Health](https://user-images.githubusercontent.com/45462483/160248866-d684b41f-4ea3-4706-892e-74d6abd95cdc.png)
![Screenshot_20220326-173746_Settings](https://user-images.githubusercontent.com/45462483/160248995-7b9c8bde-d24e-4ccb-9203-294725c5e883.jpg)

**Comment by adil192** [comment]
> ![Screenshot_20220326-173319_Samsung Health](https://user-images.githubusercontent.com/45462483/160248866-d684b41f-4ea3-4706-892e-74d6abd95cdc.png)

I'm experiencing this issue too, not sure of a fix yet
