### ISSUE TITLE
Please update the APK for Galaxy Wearable

### ISSUE THREAD

**Issue by user01515** [adil192/SamsungAppsPatcher#5]
Title says it all; Samsung pushed an update to my OG Galaxy watch (46mm), and when opening the Galaxy Wearable app, it says I need to update to continue.

**Comment by adil192** [comment]
I can't see any updates for Galaxy Wearable past the 16th April version which I have on the website https://adil.hanney.org/SamsungAppsPatcher/. Also I've just updated the OG Galaxy watch's plugin yesterday. If I had to guess, I'd say you downloaded the older apks from the mega drive and not the new website?

**Comment by user01515** [comment]
I got the apks from your website. I'll try re-installing them.

**Comment by user01515** [comment]
Due to a few things I had to reset my watch, and now it mysteriously works, with the same APK files. I guess it is good to have it working ;)
