### ISSUE TITLE
Samsung S21 Ultra Galaxy Watch Plugin Crash

### ISSUE THREAD

**Issue by maxGerards** [adil192/SamsungAppsPatcher#6]
Hello, yesterday I loaded the latest versions. Shealth works great. As soon as I want to pair my S21 Ultra with the Galaxy Watch (watchplugin.2.2.05.22042841N.apk), I get the message that the "Galaxy Watch Plugin" app has hung and the connection isn't working.

**Comment by adil192** [comment]
> I get the message that the "Galaxy Watch Plugin" app has hung and the connection isn't working.

Please can you send logs?

**Comment by maxGerards** [comment]
Where can I find the logs?

**Comment by adil192** [comment]
With this project being unmaintained, I'll close this issue. I hope someone can fork this repo and keep it alive.
