### ISSUE TITLE
Galaxy Watch3 plugin + connection is working ✓

### ISSUE THREAD

**Issue by harshil21** [adil192/SamsungAppsPatcher#7]
In your [website](https://adil.hanney.org/SamsungAppsPatcher/) you asked us to test if the Galaxy Watch3 plugin is working or not. I can confirm that it's working with version 2.2.09.22042841N.apk on my Galaxy S9 with an android 12 custom ROM. If anyone has problems make sure to also install the patched accessory service apk, along with the patched wearable app ofc.

**Comment by adil192** [comment]
Thanks
